services:
  # --- SERVICIOS DE HADOOP ---
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    networks:
      - data_network
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
      - ./data:/data
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "8020:8020"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    networks:
      - data_network
    volumes:
      - ./hadoop/datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    depends_on:
      - namenode

  # --- SERVICIOS DEL CLÚSTER DE SPARK ---
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    hostname: spark-master
    networks:
      - data_network
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    depends_on:
      - namenode
      - datanode

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    hostname: spark-worker
    networks:
      - data_network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    depends_on:
      - spark-master
  
  # --- CLIENTE INTERACTIVO JUPYTER ---
  jupyter-client:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-client
    hostname: jupyter-client
    networks:
      - data_network
    ports:
      - "8888:8888" # Interfaz de JupyterLab
      - "4040:4040" # Interfaz para los trabajos de Spark
    volumes:
      - ./apps:/home/jovyan/work/apps 
    depends_on:
      - spark-master

networks:
  data_network: