version: '3'
services:
  anaconda:
    image: continuumio/anaconda3
    container_name: notebooks
    ports:
      - "8888:8888"
    volumes:
      - ./:/opt/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: >
      /bin/bash -c "mkdir -p /opt/notebooks &&
                    jupyter notebook --notebook-dir=/opt/notebooks --ip=0.0.0.0 --no-browser --allow-root"
