# docker-compose.yml (Versión Final con Ecosistema bde2020)
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: namenode
    hostname: namenode
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
      - ./data:/data
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
      - "8020:8020"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: datanode
    hostname: datanode
    volumes:
      - ./hadoop/datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    platform: linux/amd64
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    depends_on:
      - namenode
      - datanode

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    platform: linux/amd64
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    depends_on:
      - spark-master